<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Новости");
?><?
// $APPLICATION->IncludeComponent(
// 	"bitrix:news",
// 	"",
// 	Array(
// 		"ACTIVE_DATE_FORMAT" => "d.m.Y",
// 		"ADD_SECTIONS_CHAIN" => "Y",
// 		"AJAX_MODE" => "N",
// 		"AJAX_OPTION_ADDITIONAL" => "",
// 		"AJAX_OPTION_HISTORY" => "N",
// 		"AJAX_OPTION_JUMP" => "N",
// 		"AJAX_OPTION_STYLE" => "Y",
// 		"CACHE_FILTER" => "N",
// 		"CACHE_GROUPS" => "Y",
// 		"CACHE_TIME" => "36000000",
// 		"CACHE_TYPE" => "A",
// 		"CHECK_DATES" => "Y",
// 		"DETAIL_URL" => "",
// 		"DISPLAY_BOTTOM_PAGER" => "Y",
// 		"DISPLAY_DATE" => "Y",
// 		"DISPLAY_NAME" => "Y",
// 		"DISPLAY_PICTURE" => "Y",
// 		"DISPLAY_PREVIEW_TEXT" => "Y",
// 		"DISPLAY_TOP_PAGER" => "N",
// 		"FIELD_CODE" => array("",""),
// 		"FILTER_NAME" => "",
// 		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
// 		"IBLOCK_ID" => $_REQUEST["ID"],
// 		"IBLOCK_TYPE" => "news",
// 		"INCLUDE_IBLOCK_INTO_CHAIN" => "Y",
// 		"INCLUDE_SUBSECTIONS" => "Y",
// 		"MESSAGE_404" => "",
// 		"NEWS_COUNT" => "20",
// 		"PAGER_BASE_LINK_ENABLE" => "N",
// 		"PAGER_DESC_NUMBERING" => "N",
// 		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
// 		"PAGER_SHOW_ALL" => "N",
// 		"PAGER_SHOW_ALWAYS" => "N",
// 		"PAGER_TEMPLATE" => ".default",
// 		"PAGER_TITLE" => "Новости",
// 		"PARENT_SECTION" => "",
// 		"PARENT_SECTION_CODE" => "",
// 		"PREVIEW_TRUNCATE_LEN" => "",
// 		"PROPERTY_CODE" => array("",""),
// 		"SET_BROWSER_TITLE" => "Y",
// 		"SET_LAST_MODIFIED" => "N",
// 		"SET_META_DESCRIPTION" => "Y",
// 		"SET_META_KEYWORDS" => "Y",
// 		"SET_STATUS_404" => "N",
// 		"SET_TITLE" => "Y",
// 		"SHOW_404" => "N",
// 		"SORT_BY1" => "ACTIVE_FROM",
// 		"SORT_BY2" => "SORT",
// 		"SORT_ORDER1" => "DESC",
// 		"SORT_ORDER2" => "ASC",
// 		"STRICT_SECTION_CHECK" => "N"
// 	)
// );

// $APPLICATION->IncludeComponent("bitrix:news", "template1", Array(
// 	"IBLOCK_TYPE" => "news",	// Тип инфоблока
// 		"IBLOCK_ID" => "1",	// Инфоблок
// 		"FIELD_CODE" => array("",""),
// 		"NEWS_COUNT" => "4",	// Количество новостей на странице
// 		"SORT_BY1" => "ACTIVE_FROM",	// Поле для первой сортировки новостей
// 		"SORT_ORDER1" => "DESC",	// Направление для первой сортировки новостей
// 		"CHECK_DATES" => "N",	// Показывать только активные на данный момент элементы
// 		"CACHE_TYPE" => "N",	// Тип кеширования
// 		"SEF_MODE" => "Y",	// Включить поддержку ЧПУ
// 		"SET_TITLE" => "Y",	// Устанавливать заголовок страницы
// 		"SEF_URL_TEMPLATES" => array(
// 			"news" => "",
// 			"section" => "",
// 			"detail" => "news/#ELEMENT_ID#/",
// 		)
// 	),
// 	false
// );

$APPLICATION->IncludeComponent(
	"bitrix:news", 
	"template1", 
	array(
		"IBLOCK_TYPE" => "news",
		"IBLOCK_ID" => "1",
		"NEWS_COUNT" => "4",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_ORDER1" => "DESC",
		"CHECK_DATES" => "N",
		"CACHE_TYPE" => "N",
		"SEF_MODE" => "Y",
		"SEF_FOLDER" => "/news/",
		"SET_TITLE" => "Y",
		"FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_TEXT",
			2 => "PREVIEW_PICTURE",
			3 => "DETAIL_TEXT",
			4 => "DETAIL_PICTURE",
			5 => "DATE_ACTIVE_FROM",
		),
		"LIST_FIELD_CODE" => array(
			0 => "ID",
			1 => "NAME",
			2 => "PREVIEW_TEXT",
			3 => "PREVIEW_PICTURE",
			4 => "DETAIL_TEXT",
			5 => "DETAIL_PICTURE",
			6 => "DATE_ACTIVE_FROM",
			7 => "IBLOCK_ID",
			8 => "",
		),
		"DETAIL_FIELD_CODE" => array(
			0 => "ID",
			1 => "NAME",
			2 => "PREVIEW_PICTURE",
			3 => "DETAIL_TEXT",
			4 => "DETAIL_PICTURE",
			5 => "DATE_ACTIVE_FROM",
			6 => "",
		),
		"COMPONENT_TEMPLATE" => "template1",
		"USE_SEARCH" => "N",
		"USE_RSS" => "N",
		"USE_RATING" => "N",
		"USE_CATEGORIES" => "N",
		"USE_REVIEW" => "N",
		"USE_FILTER" => "N",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"ADD_ELEMENT_CHAIN" => "N",
		"USE_PERMISSIONS" => "N",
		"STRICT_SECTION_CHECK" => "N",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"USE_SHARE" => "N",
		"PREVIEW_TRUNCATE_LEN" => "",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"DISPLAY_NAME" => "Y",
		"META_KEYWORDS" => "-",
		"META_DESCRIPTION" => "-",
		"BROWSER_TITLE" => "-",
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"PAGER_TEMPLATE" => "myPagination",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "",
		"PAGER_SHOW_ALWAYS" => "Y",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SET_STATUS_404" => "Y",
		"SHOW_404" => "Y",
		"MESSAGE_404" => "",
		"FILE_404" => "",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "",
			"detail" => "#ELEMENT_ID#/",
		)
	),
	false
);

?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>